import type { Metadata } from "next";
import Header from "@/components/basic/navabr";
import Footer from "@/components/basic/footer";
import localFont from "next/font/local"
import "./globals.css";

const myFont = localFont({
  src: [
    {
      path: "../public/fonts/KalamehWeb-Light.woff2",
      weight: "400",
      style: "light",
    },
    {
      path: "../public/fonts/KalamehWeb-Medium.woff2",
      weight: "800",
      style: "light",
    },
    {
      path: "../public/fonts/KalamehWeb-Regular.woff2",
      weight: "600",
      style: "light",
    },
  ],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${myFont.className} font-sans antialiased`}
      >
        <div className="blob-container">
          <div className="blob blob-1 w-50 h-50 lg:w-75 lg:h-75"></div>
          <div className="blob blob-2 w-37.5 h-37.5 lg:w-62.5 lg:h-62.5"></div>
          <div className="blob blob-3 w-45 h-45 lg:w-70 lg:h-70"></div>
          <div className="blob blob-4 w-40 h-40 lg:w-65 lg:h-65"></div>
        </div>
        <Header />
        <main className="mt-20 text-black">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
