import type { Metadata } from "next";
import Header from "@/components/navabr";
import Footer from "@/components/footer";
import localFont from "next/font/local"
import "./globals.css";

const myFont = localFont({
  src: [
    {
      path: "../public/fonts/KalamehWeb-Light.woff2",
      weight: "400",
      style: "light",
    },
    {
      path: "../public/fonts/KalamehWeb-Medium.woff2",
      weight: "800",
      style: "light",
    },
    {
      path: "../public/fonts/KalamehWeb-Regular.woff2",
      weight: "600",
      style: "light",
    },
  ],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${myFont.className} font-sans antialiased`}
      >
        <Header />
        <main className="mt-20 text-black">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
